In [1]:
import pandas as pd

def department_highest_salary(employee: pd.DataFrame, department: pd.DataFrame) -> pd.DataFrame:
    # 1. Находим максимальные зарплаты в каждом департаменте
    max_salaries = (
        employee.groupby("departmentId")["salary"]
        .transform("max")  # Добавляем столбец с максимальной зарплатой для каждого департамента
    )

    # 2. Фильтруем сотрудников, которые получают максимальную зарплату
    top_earners = employee[employee["salary"] == max_salaries]

    # 3. Присоединяем названия департаментов
    result = pd.merge(
        top_earners,
        department,
        left_on="departmentId",
        right_on="id",
        how="inner"
    )

    # 4. Формируем итоговую таблицу с нужными столбцами
    result = result[["name_y", "name_x", "salary"]]
    result.columns = ["Department", "Employee", "Salary"]

    return result

In [9]:
import pandas as pd

def department_highest_salary(employee: pd.DataFrame, department: pd.DataFrame) -> pd.DataFrame:
    max_salary = employee.groupby('departmentId')['salary'].transform('max')
    top_salaries = employee[employee['salary'] == max_salary]
    result = pd.merge(
        top_salaries,
        department,
        left_on = 'departmentId',
        right_on = 'id',
        how = 'inner'
    )
    result = result[['name_y', 'name_x', 'salary']]
    result.columns = ['Department', 'Employee', 'Salary']

    return result

In [ ]:
import pandas as pd
def department_highest_salary(employee, department):
    max_salaries = employee.groupby('departmentId')['salary'].transform('max')
    top_salaries = employee[employee['salary'] == max_salaries]
    result = pd.merge(
        top_salaries,
        department,
        left_on = 'departmentId',
        right_on = 'id',
        how = 'inner'
    )
    result = result['name_y', 'name_x', 'salary']
    result.columns =  ['Department', 'Employee', 'Salary']
    return result

In [10]:
# Пример данных для таблиц Employee и Department
employee_data = {
    "id": [1, 2, 3, 4, 5],
    "name": ["Joe", "Jim", "Henry", "Sam", "Max"],
    "salary": [70000, 90000, 80000, 60000, 90000],
    "departmentId": [1, 1, 2, 2, 1]
}
employee_df = pd.DataFrame(employee_data)

department_data = {
    "id": [1, 2],
    "name": ["IT", "Sales"]
}
department_df = pd.DataFrame(department_data)

# Вызов функции
result = department_highest_salary(employee_df, department_df)

# Отображение результата
print(result)

  Department Employee  Salary
0         IT      Jim   90000
1      Sales    Henry   80000
2         IT      Max   90000