In [1]:
import pandas as pd

def department_highest_salary(employee: pd.DataFrame, department: pd.DataFrame) -> pd.DataFrame:
    # 1. Находим максимальную зарплату в каждом департаменте
    max_salary_per_department = (
        employee.groupby("departmentId")["salary"]
        .max()
        .reset_index()  # Возвращаем как DataFrame для дальнейшего join
        .rename(columns={"salary": "max_salary"})
    )

    # 2. Присоединяем данные о департаментах и фильтруем сотрудников с максимальной зарплатой
    result = (
        employee
        .merge(max_salary_per_department, on="departmentId", how="inner")  # Сопоставляем максимальную зарплату
        .merge(department, left_on="departmentId", right_on="id", how="inner")  # Присоединяем названия департаментов
        .query("salary == max_salary")  # Оставляем только тех, чья зарплата равна максимальной
    )

    # 3. Формируем итоговую таблицу с нужными столбцами
    result = result[["name_y", "name_x", "salary"]]
    result.columns = ["Department", "Employee", "Salary"]

    return result

In [2]:
# Пример данных для таблиц Employee и Department
employee_data = {
    "id": [1, 2, 3, 4, 5],
    "name": ["Joe", "Jim", "Henry", "Sam", "Max"],
    "salary": [70000, 90000, 80000, 60000, 90000],
    "departmentId": [1, 1, 2, 2, 1]
}
employee_df = pd.DataFrame(employee_data)

department_data = {
    "id": [1, 2],
    "name": ["IT", "Sales"]
}
department_df = pd.DataFrame(department_data)

# Вызов функции
result = department_highest_salary(employee_df, department_df)

# Отображение результата
print(result)

  Department Employee  Salary
1         IT      Jim   90000
2      Sales    Henry   80000
4         IT      Max   90000